### ISSUE TITLE
IIFE -> Immediately Invoked Function Expression

### ISSUE THREAD

**Issue by joedietrich-dev** [learn-co-curriculum/phase-1-javascript-functions-continued#4]
Instantly should be replaced with immediately throughout this lesson when referring to IIFEs.

[MDN](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)
[Wikipedia](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

Thanks for contributing to the Flatiron School curriculum! 💙
